tiffany = User.create!(email: "tiffany@mail.com", passsword: "password", username: "Lumberjackin_Tiffany")
lauren = User.create!(email: "lauren@mail.com", passsword: "password", username: "Lumberjackin_Lauren")
james = User.create!(email: "james@mail.com", passsword: "password", username: "Lumberjackin_James")
sabri = User.create!(email: "sabri@mail.com", passsword: "password", username: "Lumberjackin_Sabri")
meagan = User.create!(email: "meagan@mail.com", passsword: "password", username: "Lumberjackin_Meagan")


question1 = Question.create!(title: "How do you shave your beard in the dark?", content: "Seriously guys, I can't see anything", user_id: 1)
question2 = Question.create!(title: "How do you shave your legs in the dark?", content: "Seriously guys, I still can't see anything", user_id: 1)
question3 = Question.create!(title: "How do you shave your dog in the dark?", content: "Seriously guys, I really need to shave my dog", user_id: 1)
question4 = Question.create!(title: "How many trees should I chop down in a day?", content: "Like if I cut down 10 trees is it enough?", user_id: 2)
question5 = Question.create!(title: "How many trees should I chop down in a week?", content: "I can cut down an entire forest in a week", user_id: 2)
question6 = Question.create!(title: "Who is going to go to prom with me?", content: "I feel like no one is going to ask me to prom", user_id: 3)
question7 = Question.create!(title: "Why does it smell like burrito at DBC right now?", content: "It smells so gross. Like so gross.", user_id: 4)
question8 = Question.create!(title: "Why are there so few lumberjacking questions on this website?!?!?!", content: "Why don't these people post their problems somewhere else?!?? OMFG", user_id: 5)

comment1 = question1.comments.create!(content: "If a tree fall in a forest...")
comment2 = question1.comments.create!(content: "...and there isn't a lumberjack to chop it down...")
comment3 = question2.comments.create!(content: "What is your favorite type of tree?")
comment4 = question1.comments.create!(content: "I enjoy the fresh smell of a cedar closet")
comment5 = question3.comments.create!(content: "I really wish there were more beard barbers in Wicker Park")
comment6 = question3.comments.create!(content: "I like to style my beard with maple syrup")
comment7 = question4.comments.create!(content: "Any tips for axe sharpening?")
comment8 = question4.comments.create!(content: "I'm a lumberjack looking for my lumberjill")
comment9 = question5.comments.create!(content: "If I'm a lumberjack, am I OK?")
comment10 = question6.comments.create!(content: "It depends. What is your favorite tartan?")
comment11 = question6.comments.create!(content: "My boots are getting soggy from all this otter blood.")